##################### GLOBAL OPTIONS

#Discord
channel: CHANNEL_ID

#Register/login options
register_time_until_kick: 60
register_max_discord_accounts: 3
register_code_length: 5
login_time_until_kick: 30
#register_custom_characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' #Only the custom added characters will appear in the +register command.
messages_only_channel: false #If true, bot will not send private messages.

#Database (sqlite or mysql)
database: 'sqlite'

#Uncomment the following if you use MYSQL
#database_username: 'user'
#database_password: 'pass'
#database_host: 'host'
#database_port: '3306'
#database_table: 'dilogin'

#Messages
discord_embed_color: '#466AC7'
discord_embed_server_image: true
discord_embed_timestamp: true
#This is the emoji codepoint. You can find it on some page like https://emojipedia.org/
#Find the emoji you want and scroll down until you find the "Codepoint" section.
discord_embed_emoji: 'U+2B50'

#Sessions
sessions: true
session_time_min: 5

#This option makes that only users with a certain role can log in.
register_required_role_enabled: false
register_required_role_id: YOUR_ROLE_ID

#Synchronization of the discord name with that of minecraft.
#When the player logs into the server, their Discord name will be changed to their Minecraft name.
#Remember bot need to have more permissions than regular users.
syncro_enable: false

#LUCKPERMS SYNCRO
#Sync minecraft server roles with discord. When a role is given on the minecraft server, 
#the corresponding one will be given on discord and vice versa.
syncro_rol_enable: false
syncro_rol_list:
       - discord_rol_id: luckperms_group_name
       - another_rol_id: another_luckperms_group_name
#EXAMPLE
#- 927608230627119184: admin


##################### ONLY FOR BUKKIT/SPIGOT/PAPER... (NOT WORK WHEN SERVER IS ON BUNGEE PROXY)

#Teleport options
teleport: false
teleport_x: -207
teleport_y: 90
teleport_z: 272
teleport_world: world
teleport_yaw: 2.4
teleport_pitch: 12.9

#COMMANDS ALIAS
register_command: 'register'

##################### BUNGEE OPTIONS
#Teleport to another server after login
teleport_server_enabled: false
teleport_server_name: 'example'