#Discord
channel: CHANNEL_ID

#Register/login options
register_time_until_kick: 60
login_time_until_kick: 30

#Messages
discord_embed_color: '#466AC7'
discord_embed_server_image: true
discord_embed_timestamp: true

#Sessions
sessions: true
session_time_min: 5