#Discord
channel: CHANNEL_ID

#Register/login options
register_time_until_kick: 60
register_max_discord_accounts: 3
register_code_length: 5
register_required_role_id: YOUR_ROLE_ID
login_time_until_kick: 30


#Teleport options
teleport: false
teleport_x: -207
teleport_y: 90
teleport_z: 272
teleport_world: world
teleport_yaw: 2.4
teleport_pitch: 12.9

#Messages
discord_embed_color: '#466AC7'
discord_embed_server_image: true
discord_embed_timestamp: true
#This is the emoji codepoint. You can find it on some page like https://emojipedia.org/
#Find the emoji you want and scroll down until you find the "Codepoint" section.
discord_embed_emoji: 'U+2B50'

#Sessions
sessions: true
session_time_min: 5