name: DILogin
main: di.dilogin.BukkitApplication
version: 4.3.1
author: Alhxe
depend: [DICore]
softdepend: [AuthMe, Multiverse-Core, LuckPerms, nLogin]
commands:
    diregister:
        description: User register
        usage: /diregister <discord_id>
        aliases: [register]
    forcelogin:
        description: Force user login
        usage: /forcelogin <nick>
        permission: sdl.forcelogin
    unregister:
        description: Unregister user
        usage: /unregister <nick>
        permission: sdl.unregister
    userinfo:
        description: User info
        usage: /userinfo <nick>
        permission: sdl.userinfo
permissions:
    sdl.forcelogin:
        description: Allow to use Forcelogin
        default: op
    sdl.unregister:
        description: Allow to use Unregister
        default: op
    sdl.userinfo:
        description: Allow to use Userinfo
        default: op
    sdl.*:
        description: Allow to use all permissions
        default: op
        children:
            sdl.forcelogin: true
            sdl.unregister: true
            sdl.userinfo: true