name: DILogin
main: di.dilogin.BukkitApplication
version: 3.0.3
author: Alhxe
api-version: 1.16
depend: [DICore]
commands:
    forcelogin:
        description: Force user login
        usage: /forcelogin <nick>
        permission: sdl.forcelogin
    unregister:
        description: Unregister user
        usage: /unregister <nick>
        permission: sdl.unregister
permissions:
    sdl.forcelogin:
        description: Allow to use Forcelogin
        default: op
    sdl.unregister:
        description: Allow to use Unregister
        default: op
    sdl.*:
        description: Allow to use all permissions
        default: op
        children:
            sdl.forcelogin: true
            sdl.unregister: true